config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/contact'
  get 'pages/about'
  devise_for :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pages
  resources :restaurants
  resources :orders
  
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_restaurant!
  def index
    @orders = Order.all
  end
   
  def new
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p id="notice" class="alert alert-primary"><%= notice %></p>
<% end %>

<% if alert %>
  <p id="alert" class="alert alert-warning"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thrive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap 5 css link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav" id="navfont">
            <li class="nav-item">
              <a class="nav-link" ><%= link_to "Home",new_restaurant_session_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" ><%= link_to "About",pages_about_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" ><%= link_to "Contact" ,pages_contact_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" ><%= link_to "Orders" ,orders_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" ><%= link_to "Sign Up" ,new_restaurant_registration_path %></a>
            </li>
            
       
            <% if restaurant_signed_in? %>
              <li class="nav-item">
                <%= link_to('Logout', destroy_restaurant_session_path, method: :delete,class: "nav-link") %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to('Login', new_restaurant_session_path, class: "nav-link") %>
              </li>
            <% end %>  
          </ul>
      <!-- 5.4 adding a log out button and the current user's email if someone is signed in, and sign up and sign in links if no one is signed in. -->
      <!-- <ul class="navbar-nav ml-auto">
        
      </ul> -->
    </div>
   
   
      </div>
    </nav>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <!-- Bootstrap 5 JS link -->
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.hidden_field :restaurant_id, value: "current.restaurant.id" %>
  </div>
  
  <div class="field">
    <%= form.label :gross_total %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.number_field :price %>
  </div>
  
  <div class="field">
    <%= form.label :discount %>
    <%= form.range_field :discount, in: 1..50 %>
  </div>
  
  <div class="field">
    <%= form.label :net_total %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="row" id = "order_disp">
  <% @orders.each do |order| %>
    <div class="col-sm" >
      <h1>Order # <%= order.id %></h1>
      <p>Restaurant ID: <%= order.restaurant_id %></p>
      <p>Gross Total: <%= order.gross_total %></p>
      <p>Tax: <%= order.tax%></p>
      <p>Discount: <%= order.discount %></p>
      <p><strong> Net Total: $<%= order.net_total %></strong></p>
    </div><!-- /col -->
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="container order_disp">
  <h1>New Order</h1>

  <%= render 'form', order: @order %>
  <%= link_to 'Back', orders_path %>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1 id="contact_header">Contact Us</h1>
<p class="contact_para">We are available at +91-9945437815 and ananya.h@gmail.com<br>
We would love to get in touch with you.</p>
<%= flash[:notice] %>
  <%= form_with(url:"/pages/thank_you", method: "post", local:
    true) do |form| %>
     <div class="container contact_form">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", placeholder:
            "Enter Name" %>
        </div>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: "form-control", placeholder:
             "Enter Email" %>
        </div>
        <div class="form-group">
          <%= form.label :message %><%= form.text_area :message, class: "form-control", placeholder:"Enter Message", rows: 5 %>
        </div>

        <%= form.submit "Send", class: "form_label" %>
       <% end %>
      </div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/thank_you.html.erb
<p>Thank you we have recieved your message.</p>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h2>Welcome to Thrive, <%= current_restaurant %> </h2>

app/views/restaurants/new.html.erb
<h2>New</h2>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<p>
  <strong>Name :</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @restaurant.email %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) , class:"bottom-l" %> |
<%= link_to 'Back', restaurants_path , class:"bottom-l" %>

</div>